apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: mysql

spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: database
      component: mysql

  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: mysql
    spec:
      containers:
      - name: mysql
        image: nagendra2244/mysql:1.0.0
        ports:
        - containerPort: 3306